name: Release to PyPI

on:
  push:
    # branches:
    #   - master
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Build package
        run: pip install build && python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
