name: Release to PyPI

on:
  push:
    branches:
      - master
    # tags:
    #   - 'v*'  # Trigger on version tags

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
